// Auto-generated by tools/generate_data.py
// DO NOT EDIT DIRECTLY

export interface Phrase {
  arabic: string;
  english: string;
  transliteration?: string;
}

export interface Dua {
  id: string;
  name: string;
  arabicName: string;
  description: string;
  level: 1 | 2 | 3;
  source: string;
  applicableDays: 'all' | number[];
  type: 'dua';
  // Content can be either phrased or block text
  phrases?: Phrase[];
  arabicText?: string;
  englishTranslation?: string;
  transliteration?: string;
  preamble?: string;
  postamble?: string;
}

export interface Aamal {
  id: string;
  name: string;
  arabicName: string;
  description: string;
  level: 1 | 2 | 3;
  source: string;
  applicableDays: 'all' | number[];
  type: 'aamal';
  timing?: string;
  instructions?: string[];
  // Content
  phrases?: Phrase[];
  arabicText?: string;
  englishTranslation?: string;
  transliteration?: string;
}

export const duas: Dua[] = [
  {
    "id": "dua_al-hajj_(the_supplication_for_pilgrimage)",
    "name": "Dua al-Hajj (The Supplication for Pilgrimage)",
    "arabicName": "",
    "description": "Recited after every obligatory prayer",
    "level": 1,
    "source": "Mafatih al-Jinan",
    "applicableDays": "all",
    "phrases": [
      {
        "arabic": "اللهُمَّ ارْزُقْنى حَجَّ بَيْتِكَ الْحَرامِ،",
        "english": "O Allah, grant me the pilgrimage to Your Sacred House,",
        "transliteration": "Allāhummar-zuqnī ḥajja baytikal-ḥarām."
      },
      {
        "arabic": "فى عامى هذا وَفى كُلِّ عامٍ،",
        "english": "In this my year and in every year,",
        "transliteration": "Fī ʿāmī hādhā wa-fī kulli ʿāmin."
      },
      {
        "arabic": "ما ابْقَيْتَنى فى يُسْرٍ مِنْكَ وَعافِيَةٍ وَسَعَةِ رِزْقٍ،",
        "english": "For as long as You keep me in ease from You, well-being, and abundance of sustenance,",
        "transliteration": "mā abqaytanī fī yusrin minka wa ʿāfiyatin wa saʿati rizqin,"
      },
      {
        "arabic": "وَلا تُخْلِنى مِنْ تِلْكَ الْمواقِفِ الْكَريمَةِ،",
        "english": "And do not deprive me of those noble stations,",
        "transliteration": "Wa-lā tukhlinī min tilka al-mawāqif al-karīmah,"
      },
      {
        "arabic": "وَالْمَشاهِدِ الشَّريفَةِ،",
        "english": "and the noble shrines,",
        "transliteration": "wal-mashāhidi ash-sharīfati,"
      },
      {
        "arabic": "وَزِيارَةِ قَبْرِ نَبِيِّكَ صَلَواتُكَ عَلَيْهِ وَآلِهِ،",
        "english": "And the visitation of the grave of Your Prophet, Your blessings be upon him and his progeny,",
        "transliteration": "wa ziyārati qabri nabiyyika ṣalawātuka ‘alayhi wa ālihi,"
      },
      {
        "arabic": "وَفى جَميعِ حَوائِجِ الدُّنْيا وَالأخِرَةِ فَكُنْ لى اللَّهُمَّ انّى اسْئَلُكَ فيما تَقْضى وَتُقَدِّرُ مِنَ الْأَمْرِ الْمَحْتُومِ فى لَيْلَةِ الْقَدْرِ،",
        "english": "And in all the needs of this world and the Hereafter, be there for me. O Allah, I beseech You concerning that which You decree and ordain of the inevitable matter on the Night of Decree,",
        "transliteration": "Wa fī jamī‘i ḥawā’ijid-dunyā wal-ākhirati fa-kun lī, Allāhumma innī as’aluka fīmā taqḍī wa tuqaddiru minal-amril-maḥtūmi fī laylatil-qadr,"
      },
      {
        "arabic": "مِنَ الْقَضآءِ الَّذى لا يُرَدُّ وَلا يُبَدَّلُ،",
        "english": "From the decree which is neither averted nor altered.",
        "transliteration": "mina al-qaḍā’i alladhī lā yuraddu wa-lā yubaddalu,"
      },
      {
        "arabic": "انْ تَكْتُبَنى مِنْ حُجَّاجِ بَيْتِكَ الْحَرامِ،",
        "english": "That You enroll me among the pilgrims of Your Sacred House,",
        "transliteration": "An taktubanī min hujjāji baytikal-ḥarāmi."
      },
      {
        "arabic": "الْمَبْرُورِ حَجُّهُمْ،",
        "english": "Whose pilgrimage is accepted,",
        "transliteration": "al-mabrūri ḥajjuhum,"
      },
      {
        "arabic": "الْمَشْكُورِ سَعْيُهُمْ،",
        "english": "Whose striving is appreciated,",
        "transliteration": "al-mashkūri sa‘yuhum,"
      },
      {
        "arabic": "الْمَغْفُورِ ذُنُوبُهُمْ،",
        "english": "Those whose sins are forgiven,",
        "transliteration": "al-maghfūri dhunūbuhum,"
      },
      {
        "arabic": "الْمُكَفَّرِ عَنْهُمْ سَيِّئاتُهُمْ،",
        "english": "Those whose sins have been expiated,",
        "transliteration": "al-mukaffari ʿanhum sayyiʾātuhum,"
      },
      {
        "arabic": "وَاجْعَلْ فيما تَقْضى وَتُقَدِّرُ انْ تُطيلَ عُمْرى وَتُوَسِّعَ عَلَىَّ رِزْقى وَتُؤدِّىَ عَنّى امانَتى وَدَيْنى آمينَ رَبَّ الْعالَمينَ.",
        "english": "And ordain, among that which You decree and predestine, that You prolong my life, expand my provision, and discharge on my behalf my trusts and my debts. Amen, O Lord of the Worlds.",
        "transliteration": "Waj‘al fīmā taqḍī wa tuqaddiru an tuṭīla ‘umrī wa tuwassi‘a ‘alayya rizqī wa tu’addiya ‘annī amānatī wa daynī. Āmīna Rabba al-‘ālamīn."
      }
    ],
    "type": "dua",
    "preamble": "Sayyid Ibn Tawus has narrated from the two Imams, al-Sadiq and al-Kadhim (peace be upon them both), that they said: \"Recite during the month of Ramadan, from its beginning until its end, after every obligatory prayer:\""
  }
];

export const aamal: Aamal[] = [];
